spring.application.name=easymarkersapp
spring.datasource.url=jdbc:mysql://localhost:3306/markersapp?useSSL=false
spring.datasource.username=markersapp
spring.datasource.password=markersapp

jwt.secret=mySuperSecretKeyForJWTThatIsAtLeast32CharactersLong1234567890
jwt.expiration.ms=26784000000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true